import Accelerate
import Foundation

public struct DecoderOptions: Sendable, Equatable {
    /// First-step fan-out: how many distinct first tokens are explored in parallel.
    public var candidates = 4
    /// First tokens below this probability are not explored.
    public var minFirstTokenProbability = 0.02
    /// After the first word, extend the suggestion word by word while each next
    /// word's probability stays at or above this. >1 disables extension.
    /// Tuned on eval seed-v1: 0.3 keeps most of the accepted-characters gain of
    /// looser values while showing far fewer wrong trailing words.
    public var extensionThreshold = 0.3
    /// Hard cap on suggested words (including the first).
    public var maxWords = 4
    /// Recommended minimum first-word confidence for showing a suggestion. The
    /// decoder itself never gates — callers compare `CompletionResult.confidence`
    /// against this (tuned on eval seed-v1; see `tabtype-eval sweep`).
    public var showThreshold = 0.2
    /// Token cap per word (guards against runaway tokens such as long numbers).
    public var maxTokensPerWord = 8

    public init() {}
}

/// One word of a suggestion with the model's probability for it (conditional on
/// everything before it).
public struct WordScore: Sendable, Equatable {
    public var text: String
    public var probability: Double
}

public struct CompletionResult: Sendable, Equatable {
    /// Text to show/insert at the caret.
    public var text: String
    /// Probability of the first word given what was typed — the confidence gate.
    public var confidence: Double
    public var words: [WordScore]
    /// Other first words the model considered, best first.
    public var alternatives: [WordScore]
    /// The model expects a space after the last suggested word.
    public var predictedTrailingSpace: Bool
    public var promptTokens: Int
    public var generatedTokens: Int
}

/// Confidence-scored completion on raw logits: token healing, parallel first-word
/// candidates, duplicate merging, and probability-gated phrase extension.
public enum CompletionDecoder {
    /// - Parameter text: everything before the caret, as it should be continued
    ///   (context included). The typed text must be at its very end.
    /// - Parameter isCancelled: polled between decode steps; a true result aborts.
    public static func complete(_ text: String, model: TokenModel, options: DecoderOptions = DecoderOptions(),
                                isCancelled: @escaping () -> Bool = { false }) throws -> CompletionResult? {
        var split = HealSplit.split(text)
        var promptTokens = model.tokenize(split.prompt, addSpecial: true)
        // Heal bytes no single token can start (exotic scripts/byte runs): fall back
        // to continuing the raw text unhealed.
        if !split.heal.isEmpty, model.vocab.tokens(consistentWith: split.heal[...]).isEmpty {
            split = HealSplit(prompt: text, heal: [])
            promptTokens = model.tokenize(text, addSpecial: true)
        }
        guard !promptTokens.isEmpty else { return nil }

        var session = Session(model: model, options: options, heal: split.heal,
                              promptLength: promptTokens.count, isCancelled: isCancelled)
        defer { session.dropSequences() }
        let logits = try model.evaluatePrompt(promptTokens)
        return try session.run(promptLogits: logits)
    }
}

// MARK: - Search

private struct Candidate {
    var sequence: Int
    var tokens: [TokenID] = []
    /// All generated bytes, heal included.
    var bytes: [UInt8] = []
    var pendingHeal: ArraySlice<UInt8>
    var logProbability: Double = 0
    var finished = false
    /// The token chosen but not fed when the word ended — the next word's start.
    var stopToken: TokenID?
    var stopLogProbability: Double = 0
    var logits: Logits?
}

private struct Session {
    let model: TokenModel
    let options: DecoderOptions
    let heal: [UInt8]
    let promptLength: Int
    let isCancelled: () -> Bool
    var usedSequences: [Int] = []
    var scratch: [Float] = []
    var generated = 0

    init(model: TokenModel, options: DecoderOptions, heal: [UInt8], promptLength: Int,
         isCancelled: @escaping () -> Bool) {
        self.model = model
        self.options = options
        self.heal = heal
        self.promptLength = promptLength
        self.isCancelled = isCancelled
    }

    var vocab: VocabIndex { model.vocab }

    mutating func dropSequences() {
        for seq in usedSequences { model.drop(sequence: seq) }
        usedSequences.removeAll()
    }

    // MARK: Stage A — first word, candidates in parallel

    mutating func run(promptLogits: Logits) throws -> CompletionResult? {
        let healSlice = heal[...]
        let allowed = heal.isEmpty ? nil : vocab.tokens(consistentWith: healSlice)
        let norm = normalizer(promptLogits, allowed: allowed)
        let fanOut = min(options.candidates, model.maxSequences - 1)
        // Suggestions continue the current line; never open with a line break.
        var firsts = LogitMath.topK(promptLogits, k: fanOut, candidates: allowed, blocked: vocab.blocked)
            .filter { !vocab.containsNewline($0) }
            .filter { exp(Double(promptLogits.values[Int($0)] - norm)) >= options.minFirstTokenProbability }
        if firsts.isEmpty, let best = LogitMath.topK(promptLogits, k: 1, candidates: allowed, blocked: vocab.blocked).first {
            firsts = [best]
        }
        guard !firsts.isEmpty else { return nil }

        var candidates: [Candidate] = []
        var entries: [BatchEntry] = []
        for (i, token) in firsts.enumerated() {
            let seq = i + 1
            model.fork(to: seq)
            usedSequences.append(seq)
            var c = Candidate(sequence: seq, pendingHeal: healSlice)
            let lp = Double(promptLogits.values[Int(token)] - norm)
            // A first token can itself end the word immediately (heal fully
            // consumed and the token already holds a complete word + boundary is
            // decided on the NEXT token), so it is always fed.
            append(token, logProbability: lp, to: &c)
            candidates.append(c)
            entries.append(BatchEntry(token: token, position: promptLength, sequence: seq))
        }
        try feed(entries, into: &candidates, indices: Array(candidates.indices))

        while candidates.contains(where: { !$0.finished }) {
            if isCancelled() { throw CancellationError() }
            var batch: [BatchEntry] = []
            var batchOwners: [Int] = []
            for i in candidates.indices where !candidates[i].finished {
                guard let next = choose(for: candidates[i]) else {
                    candidates[i].finished = true
                    continue
                }
                if shouldEndWord(candidates[i], before: next.token) {
                    candidates[i].finished = true
                    // Only a whitespace-led token starts a next word worth extending into.
                    let startsWord = vocab.startsWithWhitespace(next.token) && !vocab.containsNewline(next.token)
                    candidates[i].stopToken = startsWord ? next.token : nil
                    candidates[i].stopLogProbability = next.logProbability
                    continue
                }
                append(next.token, logProbability: next.logProbability, to: &candidates[i])
                batch.append(BatchEntry(token: next.token,
                                        position: promptLength + candidates[i].tokens.count - 1,
                                        sequence: candidates[i].sequence))
                batchOwners.append(i)
            }
            try feed(batch, into: &candidates, indices: batchOwners)
        }

        // Merge candidates that render the same visible text (different
        // tokenizations of one word), summing their probability mass.
        var merged: [(text: String, logP: Double, index: Int)] = []
        for (i, c) in candidates.enumerated() {
            let text = visibleText(c)
            guard text.contains(where: { !$0.isWhitespace }) else { continue }
            if let j = merged.firstIndex(where: { $0.text == text }) {
                merged[j].logP = logAddExp(merged[j].logP, c.logProbability)
            } else {
                merged.append((text, c.logProbability, i))
            }
        }
        merged.sort { $0.logP > $1.logP }
        guard let best = merged.first else { return nil }

        var winner = candidates[best.index]
        var words = [WordScore(text: best.text, probability: exp(best.logP))]
        try extend(&winner, words: &words)

        let text = words.map(\.text).joined()
        return CompletionResult(
            text: text,
            confidence: exp(best.logP),
            words: words,
            alternatives: merged.dropFirst().prefix(3).map { WordScore(text: $0.text, probability: exp($0.logP)) },
            predictedTrailingSpace: winner.stopToken.map { vocab.pieces[Int($0)].first == 0x20 } ?? false,
            promptTokens: promptLength,
            generatedTokens: generated)
    }

    // MARK: Stage B — extend the winner word by word while confident

    mutating func extend(_ c: inout Candidate, words: inout [WordScore]) throws {
        while words.count < options.maxWords, options.extensionThreshold <= 1 {
            guard let start = c.stopToken, !vocab.containsNewline(start) else { return }
            if isCancelled() { throw CancellationError() }
            var wordBytes = vocab.pieces[Int(start)]
            var wordLogP = c.stopLogProbability
            var token = start
            var tokensInWord = 0
            c.stopToken = nil
            while true {
                let logits = try model.decode([BatchEntry(token: token, position: promptLength + c.tokens.count,
                                                          sequence: c.sequence)])[0]
                c.tokens.append(token)
                generated += 1
                tokensInWord += 1
                guard let next = greedy(logits) else { break }   // end of generation
                if vocab.startsWithWhitespace(next.token) || vocab.containsNewline(next.token)
                    || tokensInWord >= options.maxTokensPerWord {
                    c.stopToken = next.token
                    c.stopLogProbability = next.logProbability
                    break
                }
                wordBytes += vocab.pieces[Int(next.token)]
                wordLogP += next.logProbability
                token = next.token
            }
            let probability = exp(wordLogP)
            guard probability >= options.extensionThreshold else { return }
            words.append(WordScore(text: String(decoding: wordBytes, as: UTF8.self), probability: probability))
        }
    }

    // MARK: Steps

    struct Choice { var token: TokenID; var logProbability: Double }

    /// The next token for a candidate: constrained to the remaining heal while it
    /// lasts, greedy afterwards. nil when the model wants to end here.
    mutating func choose(for c: Candidate) -> Choice? {
        guard let logits = c.logits else { return nil }
        if !c.pendingHeal.isEmpty {
            let allowed = vocab.tokens(consistentWith: c.pendingHeal)
            guard let token = LogitMath.topK(logits, k: 1, candidates: allowed, blocked: vocab.blocked).first else {
                return nil
            }
            let norm = LogitMath.logSumExp(logits, over: allowed)
            return Choice(token: token, logProbability: Double(logits.values[Int(token)] - norm))
        }
        return greedy(logits)
    }

    /// Unconstrained greedy step over the whole vocabulary. nil when the best token
    /// is a control/end-of-generation token.
    mutating func greedy(_ logits: Logits) -> Choice? {
        var maxValue: Float = 0
        var maxIndex: vDSP_Length = 0
        vDSP_maxvi(logits.values.baseAddress!, 1, &maxValue, &maxIndex, vDSP_Length(logits.values.count))
        let token = TokenID(maxIndex)
        guard !vocab.blocked[Int(token)] else { return nil }
        let norm = LogitMath.logSumExp(logits, blocked: nil, scratch: &scratch)
        return Choice(token: token, logProbability: Double(maxValue - norm))
    }

    func shouldEndWord(_ c: Candidate, before token: TokenID) -> Bool {
        guard c.pendingHeal.isEmpty else { return false }
        if vocab.endOfGeneration[Int(token)] { return true }
        let visible = visibleBytes(c)
        let hasContent = visible.contains { $0 != 0x20 && $0 != 0x0A && $0 != 0x09 }
        if vocab.containsNewline(token) { return true }
        if hasContent, vocab.startsWithWhitespace(token) { return true }
        return c.tokens.count >= options.maxTokensPerWord + 2
    }

    mutating func append(_ token: TokenID, logProbability: Double, to c: inout Candidate) {
        let piece = vocab.pieces[Int(token)]
        c.tokens.append(token)
        c.bytes += piece
        c.logProbability += logProbability
        if !c.pendingHeal.isEmpty {
            c.pendingHeal = piece.count >= c.pendingHeal.count ? [][...] : c.pendingHeal.dropFirst(piece.count)
        }
        generated += 1
    }

    mutating func feed(_ entries: [BatchEntry], into candidates: inout [Candidate], indices: [Int]) throws {
        guard !entries.isEmpty else { return }
        let logits = try model.decode(entries)
        for (k, i) in indices.enumerated() { candidates[i].logits = logits[k] }
    }

    mutating func normalizer(_ logits: Logits, allowed: [TokenID]?) -> Float {
        if let allowed { return LogitMath.logSumExp(logits, over: allowed) }
        return LogitMath.logSumExp(logits, blocked: nil, scratch: &scratch)
    }

    func visibleBytes(_ c: Candidate) -> ArraySlice<UInt8> {
        c.bytes.count > heal.count ? c.bytes[heal.count...] : []
    }

    func visibleText(_ c: Candidate) -> String {
        String(decoding: visibleBytes(c), as: UTF8.self)
    }
}

private func logAddExp(_ a: Double, _ b: Double) -> Double {
    let m = max(a, b)
    return m + log(exp(a - m) + exp(b - m))
}
